### ISSUE TITLE
Reset application state before each EarlGrey test?

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#103]
What's the recommend approach for resetting the application state before each test? I'm thinking of issues such as:
- logging out
- dismissing any app specific dialogs

- [discussion group topic](https://groups.google.com/forum/#!topic/earlgrey-discuss/8JpItL8e7kk)

**Comment by bootstraponline** [comment]
If we had XCUITest support then we could just relaunch the app.

**Comment by khandpur** [comment]
FWIW, we're still working on XCUITest support design and plan on sharing that doc on Slack for feedback.

I don't quite agree that XCUITest alone will solve all these problems (more details below).

For the recommended approach to reset the app, you'd need to:
1) Logout:
This is useful if you want to test different login flows but if you just care about getting past the sign-in screen, structure the tests in a way so that if the login screen is shown, it will try to login otherwise assert that the main screen is shown. Alternatively, a better approach would be to fake out the login flow (for tests that don't care about login scenario). Keep in mind that keychain entries will be persisted so even with XCUITest you'd have to somehow make sure it's faked out or works with App that's already signed in.
2) Dismiss dialogs
This should be done as part of the tearDown. You can tell if a dialog is shown by inspecting the ui hierarchy.
3) Make sure all the persistent state is cleared so app starts in a clean state: This would involve some work. The best way would be to bake a resetApplication method in the app delegate which resets services, databases, tears down windows and recreates them in a clean state. Even XCUITest will suffer from this because app has persistent data which survives subsequent launches.

**Comment by bootstraponline** [comment]
> bake a resetApplication method in the app delegate which resets services, databases, tears down windows and recreates them in a clean state.

That makes sense. Thanks for the explanation.

**Comment by khandpur** [comment]
Any other updates on this? Is it safe to close?

**Comment by bootstraponline** [comment]
Closed.
