### ISSUE TITLE
UI flashes on grey_tap()

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#390]
grey_tap will cause excessive UI flashing.

**Comment by sid-github** [comment]
Is it just tap, or does swipe and scroll also cause this?

**Comment by bootstraponline** [comment]
I have no idea. I only tested with tap. Apparently @khandpur has a fix that's being worked on.

**Comment by sskhandp** [comment]
I looked into fixing it but due to the way visibility checker works, all of the solutions added a small amount of flash. Given that iOS 10.3 fixed [drawViewHierarchyInRect:afterScreenUpdates:YES](https://developer.apple.com/reference/uikit/uiview/1622589-drawviewhierarchyinrect?language=objc) to not flash when there are un-flushed committed CATransactions, I think we can close this bug with a note that it's fixed in iOS 10.3

Could you also verify on your end before I close this bug?

**Comment by bootstraponline** [comment]
looks fixed to me, nice work!
