### ISSUE TITLE
EarlGrey runs slower compared to KIF/XCUITEST

### ISSUE THREAD

**Issue by yaphatak** [google/EarlGrey#471]
`Mac OS : 10.11.6
iOS : 10.2
EarlGrey: 1.6`

If I change setting to `(GREYConfiguration.sharedInstance() as AnyObject).setValue(false, forConfigKey: kGREYConfigKeySynchronizationEnabled)`, Its much faster

**Comment by khandpur** [comment]
@yaphatak  What scenarios?

**Comment by yaphatak** [comment]
I just created for @tirodkar . Issue is actually raised by ahmedeid from Slack.

**Comment by tirodkar** [comment]
++ https://github.com/AhmedEid

**Comment by sskhandp** [comment]
I don't have Ahmed's github id so unable to tag him on here...

@tirodkar Could you please find out which scenarios and/or actions this is referring to?

**Comment by tirodkar** [comment]
Actually, I'm closing this now. The issue is visible with XCUITest / running a regular app as well on my machine and seems to be independent to EarlGrey.

The test in question was slow because of the order of matchers being passed in. grey_sufficientlyVisible() was the first matcher in grey_allOf(), IIRC.
