### ISSUE TITLE
Keyplane change need one more tap to proceed

### ISSUE THREAD

**Issue by krzyzanowskim** [google/EarlGrey#633]
Looks like typing on the simulator, on the very fresh simulator (iOS11) pause on keyplane change due to one more element to tap to proceed (see screenshot). This screenshot was taken when I tap some letters and tried to type the first number.

https://github.com/google/EarlGrey/blob/master/EarlGrey/Core/GREYKeyboard.m#L228

![screen shot 2017-09-25 at 13 07 49](https://user-images.githubusercontent.com/758033/30807578-cc0b6150-a1fa-11e7-8508-42f59a604e0b.png)

Xcode: Version 9.0 (9A235)
Simulator: iPad Pro (2nd generation)

**Comment by steipete** [comment]
If anyone knows of a magical environment variable or define that disables tutorials in iOS, that would be the place for it. Otherwise we could open a DTS to ask, or just (worst case) check for that state specifically.

Digging into UIKit, `-[UIGestureKeyboardIntroduction showGestureKeyboardIntroduction]` is responsible for this UI, so likely we can also swizzle it away.

It seems to be called by `-[UIKeyboardLayoutStar showGestureKeyboardIntroductionIfNeeded]`

There's also `[UIKeyboardLayoutStar shouldShowGestureKeyboardIntroduction]`

This checks if the bundle ID is `com.apple.purplebuddy` and prevents showing in that case... but that's really not an option (also, wth?)

It also queries the `UIKeyboardPreferencesController`, but seems a bit tricky to store that:

```
  if ( objc_msgSend(*(void **)((char *)&self->super.super._safeAreaInsets.var3 + 1), "keyboardAppearance", v2) == &stru_68.segname[7] )
    return 0;
  v3 = +[UIKeyboardPreferencesController sharedPreferencesController](
         &OBJC_CLASS___UIKeyboardPreferencesController,
         "sharedPreferencesController");
  v4 = objc_msgSend(v3, "preferencesActions");
  if ( !(unsigned __int8)objc_msgSend(v4, "boolForPreferenceKey:", UIKBInputGesturesEnabled[0]) )
    return 0;
```

I'd just swizzle `-[UIKeyboardLayoutStar showGestureKeyboardIntroductionIfNeeded]` to fix it.

**Comment by krzyzanowskim** [comment]
maybe this is the setting

```
[[TIPreferencesControllerClient sharedPreferencesController] _configureKey:@"DidShowGestureKeyboardIntroduction" domain:@"com.apple.Preferences" defaultValue:@(NO)];
```

**Comment by steipete** [comment]
Filed Radar http://openradar.appspot.com/34634970 - dupes welcome.

**Comment by tirodkar** [comment]
Thanks for bringing this up @krzyzanowskim. We could also add that as part of EarlGrey's Automation Setup where we disable amongst other things, Predictive Text and AutoComplete.
