### ISSUE TITLE
Simple test failing with timeout because of AFNetworking probably?

### ISSUE THREAD

**Issue by wojczitsu** [google/EarlGrey#689]
`EarlGrey.select(elementWithMatcher: grey_keyWindow()).assert(grey_sufficientlyVisible())`
fails with 
```
Exception Name: TimeoutException
Exception Reason: Timed out while waiting to perform assertion.
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher:matcherForSufficientlyVisible(>=0.750000)",
  "Element Matcher" : "(kindOfClass('UIWindow') && keyWindow)"
}

Exception Details: Error Trace: [
  {
    "Description" : "Failed to execute block because idling resources below are busy.",
    "Description Glossary" :     {
      "performSelector @selector(update) on StatusBarViewController" : "Delayed performSelector caused the App to be in busy state for 2 seconds."
    },
    "Error Domain" : "com.google.earlgrey.GREYUIThreadExecutorErrorDomain",
    "Error Code" : "0",
    "File Name" : "GREYUIThreadExecutor.m",
    "Function Name" : "-[GREYUIThreadExecutor executeSyncWithTimeout:block:error:]",
    "Line" : "239",
    "TestCase Class" : "TMPL.LoginTest",
    "TestCase Method" : "testExample"
  }
```
Check this issue also:
https://github.com/AFNetworking/AFNetworking/issues/4045

**Comment by khandpur** [comment]
Have you set the timeout to < 2 seconds?

The idling resource that's reported in the logs:
`
"performSelector @selector(update) on StatusBarViewController" : "Delayed performSelector caused the App to be in busy state for 2 seconds."
`

is associated with performSelector call on the main thread. Any chance it's being spammed? For instance perform selector foo ends up calling perform selector foo again? In that case earlgrey waits for 2 seconds for foo to execute but since it triggers another call to foo in 2 seconds, earlgrey ways again.

One thing you can do is set [kGREYConfigKeyDelayedPerformMaxTrackableDuration](https://github.com/google/EarlGrey/blob/499474e02cc486b65c360da362173ec77e7495ee/EarlGrey/Common/GREYConfiguration.h#L97) to a much lower value.
