### ISSUE TITLE
Publish configure_earlgrey_pods.rb as a gem & add carthage support

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#73]
It'd be nice if configure_earlgrey_pods.rb was published as a gem and supported carthage. Manual setup with carthage is painful.

**Comment by bootstraponline** [comment]
The gem could also setup a bridging header and `EarlGrey.swift`

**Comment by bootstraponline** [comment]
related to #72 

I have setup [an example project](https://github.com/bootstraponline/swift_xcuitest_example/) that has EarlGrey configured manually using carthage in the `ExampleEarlGrey` target. 

The `AutoEarlGrey` is empty and I published [an EarlGrey gem](https://github.com/bootstraponline/earlgrey) that auto configures the target.

I still have to add some tests but the code works (at least for the carthage use case). In addition to carthage support via the CLI, it'll also help Cocoapods. Instead of `load('configure_earlgrey_pods.rb')`, you can just `require 'earlgrey'`. This is easier than manually copying Ruby code.

Let me know what you think. I'm happy to donate the repo to the google org if you'd be willing to help maintain it.

**Comment by khandpur** [comment]
Having a published gem would mean that we can fix bugs on the fly and republish the gems without having the user to go through tedious steps of manually copying over the rb file =)

We'd be happy to help maintain it but would it be possible to have them in the same repo? Otherwise, I'll have to check what the guidelines are for taking ownership over other repos and might have to seek approval for it.

**Comment by bootstraponline** [comment]
Sure, we can keep it in the same repo. I'll work on a pull request.
