### ISSUE TITLE
EarlGrey 2.0 | Cocoapods | Can't run target app without UITests

### ISSUE THREAD

**Issue by konrad-zdunczyk-luxmed** [google/EarlGrey#971]
Target app crashes on start if run alone (without UITests ex. by hitting cmd+R) and get

> Fatal failure: EarlGrey's app component has been launched without edoPort assigned. You are probably running the application under test by itself, which does not work since the embedded EarlGrey component needs its test counterpart present.  in /Users/brettfazio/dev/reducingimports/EarlGrey/AppFramework/DistantObject/GREYHostApplicationDistantObject.m:93

It can be reproduce in Example from earlgrey2 branch.

Xcode 10.2.1
Swift 5.0
Cocoapods 1.6.1

**Comment by richgui-carrot** [comment]
I just ran into this exact same error this week.

**Comment by RichardGuion** [comment]
I ran into the same exact error this week.

**Comment by tirodkar** [comment]
Can you do a clean build and then run it? Basically, you're running it on a version of your app with EG's AppFramework still linked in.

**Comment by RichardGuion** [comment]
I reproduced on the EarlGreyExample for 2.0. When it run the app standalone I get the error described above. I cleaned the build folder, even deleted DerivedData, then hit Run to install on the simulator. Same crash. Clean then Build for Running, same crash again.

**Comment by RichardGuion** [comment]
I see that in the code here:
https://github.com/google/EarlGrey/blob/earlgrey2/TestLib/XCTestCase/XCUIApplication+GREYEnvironment.m#L23

I had to read up on DYLD_INSERT_LIBRARIES. Very cool how this works.

But I cannot explain why the app still crashes running standalone on a clean build without the tests. I created a separate scheme just for the tests and the app together. I had a second scheme with just the app itself, no tests, no EarlGrey. Even after cleaning DerivedData and building from scratch, I still received the error.

**Comment by jainhitesh3** [comment]
Hi @tirodkar : When can we expect a fix/workaround for this issue?

**Comment by tirodkar** [comment]
Is the bundle id the same for both apps? Can you please ensure they are different?

**Comment by RichardGuion** [comment]
@tirodkar I looked at the Pods project and saw that they are different...is this where you wanted us to look? 

<img width="560" alt="EarlGreyApp bundle ID" src="https://user-images.githubusercontent.com/4001013/65987421-9d4fce80-e43a-11e9-8cea-90b91551b6ec.png">
<img width="574" alt="EarlGreyTest bundle ID" src="https://user-images.githubusercontent.com/4001013/65987436-a5a80980-e43a-11e9-84dd-86a28dda7636.png">

**Comment by tirodkar** [comment]
No. I was talking about your application being tested.

**Comment by RichardGuion** [comment]
I'm just using the EarlGrey demo, which reproduces the problem. The bundle id for the app vs the tests are different.
<img width="903" alt="EarlGreyExampleSwift bundle" src="https://user-images.githubusercontent.com/4001013/65988492-cd986c80-e43c-11e9-99ee-926400750d1d.png">
<img width="704" alt="EarlGreyExampleSwiftUITests bundle" src="https://user-images.githubusercontent.com/4001013/65988497-cffac680-e43c-11e9-9e70-92532afab5b0.png">

**Comment by RichardGuion** [comment]
@brettfazio - wondering if you could give us any insight here?

**The problem:** Cocoapods installs EG2 just fine and allows us to run the tests. However the app itself can no longer be run stand-alone, because the app links in AppFramework.framework directly all the time. This leads to the error message when launching the app (outside the UI tests) _"EarlGrey's app component has been launched without edoPort assigned._" We can all reproduce this using the EG2 demo EarlGreyExample in the repo.

I see this in the podspec for EarlGreyApp: 
https://github.com/google/EarlGrey/blob/earlgrey2/EarlGreyApp.podspec#L19

This translates to the linker setting we see in the project for the **EarlGreyExampleSwift** app in the demo after we do **_'pod install'_**
<img width="921" alt="Cocoapod app target linker setting" src="https://user-images.githubusercontent.com/4001013/66090632-264d2f80-e539-11e9-8659-5b0ee37621e8.png">

With this setting you can see, any time the app is launched, this component is part of the app, and the missing edoPort throws that exception I mentioned above, when executed without the companion test app.

I was wondering why we don't do the Copy Files method in the setup description for the cloning repo method in the setup docs: https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md

![Copy AppFramework](https://user-images.githubusercontent.com/4001013/66090826-e6d31300-e539-11e9-8a01-c1a740fd8399.png)

This method leaves the app target alone and copies over AppFramework.framework after the test target is built.

Regardless, with the pod version, I did an experiment. I removed the linker setting for AppFramework.framework in the app target.

![xcconfig file remove appframeworks](https://user-images.githubusercontent.com/4001013/66090891-2a2d8180-e53a-11e9-96ed-63b0cda2f3e9.png)

I removed it from Pods-EarlGreyExampleSwift.debug.xcconfig. Cleared my DerivedData folder, rebuilt the tests, and the tests ran fine. But I was also, for the first time, able to launch the EarlGreyExampleSwift app standalone!

![linker flag AppFramework gone](https://user-images.githubusercontent.com/4001013/66091028-c2c40180-e53a-11e9-9108-c25e5094ccd3.png)

Not sure why it works...but it does. I did double check to make sure I am still running in Debug mode.

**Comment by brettfazio** [comment]
@RichardGuion If you take a look at either of the Podspecs neither of them add the "-Objc" flag or the  "-framework "AppFramework"" flag. So I believe that to be added automatically.

**Comment by RichardGuion** [comment]
@brettfazio yes - I think it is added by 

`s.vendored_frameworks = "AppFramework.framework"`

**Comment by brettfazio** [comment]
@RichardGuion the line you pointed out [here](https://github.com/google/EarlGrey/blob/earlgrey2/EarlGreyApp.podspec#L19) is necessary because without it the Framework would not be linked in. So I don't believe that to be the culprit there.

If the goal here is to only have AppFramework link on one of the two, in the case you pointed out not having it link on "Debug", I believe that https://guides.cocoapods.org/syntax/podfile.html#project could be of some use.

There is stuff in there that speaks on ":Debug" and ":Release" so potentially a modification to EarlGreyApp.podspec could be made using those project custom build configurations.

**Comment by jainhitesh3** [comment]
Hi @brettfazio / @tirodkar: Is there any update on this? Is there a plan to pick this issue anytime soon? If not could you please tell if there is any workaround that can be done to solve this?

**Comment by tirodkar** [comment]
@jainhitesh3 this is by design with EG. We have to embed EarlGrey into your application for testing it. 

When you add the EarlGreyApp component to your application and then generate the CocoaPods workspace, your entire application target now contains the App component inside it. Regardless of a clean build, deleted derived data etc - every time you launch the application, it is launching with any EG related flags / binaries that have been added in the Podfile.

As @RichardGuion showed - you could modify the Build Settings in the workspace and get your application to launch by itself. You can then do a new `pod update` to run the tests. Alternatively, you can duplicate your application target and use that as the `Target Host` with your EG tests.

**Comment by jainhitesh3** [comment]
@tirodkar: I tried the steps mentioned by @RichardGuion. I'm able to run my target app independently (without launching any tests).

Also as suggested by @brettfazio in the above comment, is it possible to update EarlGreyApp.podspec file, and specify if we need this framework for ":Debug" or ":Release"?

**Comment by bingwen2019** [comment]
Is there any update on this?
Still crash when running the app standalone.

EarlGrey 2.2.0
Xcode 12

**Comment by tirodkar** [comment]
With 2.2.0 - we have an update on this. You can specify `EarlGreyStandaloneMode`: `1` in your Scheme's Environment Variables and you can run your application with EarlGrey's app component linked in.

**Comment by christianmierez** [comment]
@tirodkar great to know this was fixed! It'd be also great to update the [setup](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md) doc with this information.
